### ISSUE TITLE
HUSE in Exiobase has information on product country of origin, we miss an activity type for that

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/rdf#4]
the file
` rdf/activitytype/exiobase3_3_17/exiobase3_3_17.ttl`

should define an activity type for modeling the origin of flows of products in the use table.

E.g., the Motor Gasoline from Belgium is supplied to Australia wheat production

This come from a discussion with Søren.

**Comment by boweidema** [comment]
The current ontology already allows a flow to be bont:outputOf one activity and bont:inputOf another activity. But for the SUT, the product flow origin is redundant information that should be ignored. In a true SUT, the flows enter and leave an activity but do not yet have information on their origin and destination. This information is added when linking the different activities into a Direct Requirements Matrix. The EXIOBASE SUT is overspecified in this sense that it already has interpreted the information in the trade statistics in a specific (attributional) way. This error should not be imported into the BONSAI implementation, which should leave the user free to link SUT activities with different linking algorithms (including one that we may decide on being the preferred consensus one for "official" BONSAI footprints).

**Comment by kuzeko** [comment]
Just to clarify, given the current EXIOBASE excel file, there are rows where an activity X  recieves as input some flow object Y from two sources (assume water for paddy rice cultivation, it reiceves a quantity of M water from source 1 and then a quantity of N water from source 2  ).

There are then 2 options:
1- accept that there are two inputs in the EXIOBASE and materialize those two so not to lose information
2- aggregate back all quantities in a single input quantity. Option 2 actively "removes" information.

**Comment by kuzeko** [comment]
It has been decided for option 2 (see https://github.com/BONSAMURAIS/EXIOBASE-conversion-software/issues/3)

This can be closed now.
